server:
  port: 8080
  servlet:
    context-path: /nepm

logging:
  level:
    org.springframework: info
    com.neusoft.nepm.mapper: debug

spring:
  application:
    name: nepm
  profiles:
    active: dev
  #  main:
  #    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

redis:
  host: localhost # Redis服务器地址
  database: 0 # Redis数据库索引（默认为0）
  port: 6379 # Redis服务器连接端口
  password: # Redis服务器连接密码（默认为空）
  jedis:
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
  timeout: 3000ms # 连接超时时间（毫秒）


captcha:
  width: 200
  height: 100
  session:
    key: CAPTCHA_SESSION_KEY
    date: CAPTCHA_SESSION_DATE

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /admins/getAdminsByCode
      - /admins/adminsRegister
      - /admin/info
      - /admin/logout

jackson:
  data-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8
#jwt:
#  tokenHeader: Authorization #JWT存储的请求头
#  secret: mall-admin-secret #JWT加解密使用的密钥
#  expiration: 604800 #JWT的超期限时间(60*60*24*7)
#  tokenHead: 'Bearer '  #JWT负载中拿到开头